title: The Urarina Digital Heritage Project
#Laenanuuinelanaala jelaia Urarina kainara kuina amiianena
#subtitle: The Urarina Digital Heritage Project
author:
  name: 
  email: 
description:
  The Urarina Digital Heritage Project is a collaborative, international effort that makes Urarina cultural heritage items held at the University of Kansas accessible in multilingual form to the general public and to the Urarina community in the Peruvian Amazon from which they originated. 
baseurl: "/urarina-wax"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: false
  urarina: # name of collection
    output: true # makes sure pages are output as html files
    layout: "urarina_item" # the layout for the pages to use
    metadata:
      source: "urarina-metadata-wax.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/urarina" # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      urarina:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - description
          - label
          - type
          - subject
          - material

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "Welcome"
    link: "pages/welcome.html"
  - label: "Browse"
    link: "pages/collection.html"
  - label: "Search"
    link: "/search/"
  - label: "About"
    sub:
      - label: "The Urarina Digital Heritage Project"
        link: "pages/about.html"
      - label: "Credits"
        link: "pages/credits.html"
      - label: "Resources"
        link: "pages/resources.html"
      - label: "Rights & Reuse"
        link: "pages/rights.html"
      - label: "Building the Site"
        link: "pages/learning.html"

plugins:
  - jekyll-multiple-languages-plugin

# Extras for multi language support
# https://github.com/kurtsson/jekyll-multiple-languages-plugin
languages: ["en", "es", "ur"]
exclude_from_localizations: ["javascript", "images", "css"]

# In code, these specific files should be referenced via baseurl_root. E.g.
# <link rel="stylesheet" href="{{ "/css/bootstrap.css" | prepend: site.baseurl_root }}"/>

#If you wish to avoid having the default_lang built into the root of your website, use:
#default_locale_in_subfolder: true
default_locale_in_subfolder: false




